use_frameworks!

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'HQYNetWorking_Example' do
  pod 'HQYNetWorking', :path => '../'

  target 'HQYNetWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
